-- Populate Education Levels
INSERT INTO education_levels (level_name) VALUES 
('Elementary Graduate'),
('High School Graduate'),
('Junior High School Graduate'),
('Senior High School Graduate'),
('Vocational Diploma / Short Course Certificate'),
('Bachelor\'s/College Degree'),
('Post Graduate Diploma / Master\'s Degree'),
('Professional License (Passed Board/Bar/Professional License Exam)'),
('Doctorate Degree');

-- Populate Courses / Strands
INSERT INTO courses (course_name) VALUES 
('Senior High: Accountancy, Business and Management (ABM)'),
('Senior High: Science, Technology, Engineering and Mathematics (STEM)'),
('Senior High: Humanities and Social Sciences (HUMSS)'),
('Senior High: General Academic Strand (GAS)'),
('Senior High: Technical-Vocational-Livelihood (TVL)'),
('Senior High: Arts and Design'),
('Senior High: Sports'),
('Bachelor of Science in Information Technology (BSIT)'),
('Bachelor of Science in Computer Science (BSCS)'),
('Bachelor of Science in Information Systems (BSIS)'),
('Bachelor of Science in Business Administration (BSBA)'),
('Bachelor of Science in Accountancy (BSA)'),
('Bachelor of Science in Management Accounting (BSMA)'),
('Bachelor of Science in Civil Engineering (BSCE)'),
('Bachelor of Science in Mechanical Engineering (BSME)'),
('Bachelor of Science in Electrical Engineering (BSEE)'),
('Bachelor of Science in Electronics Engineering (BSECE)'),
('Bachelor of Science in Computer Engineering (BSCpE)'),
('Bachelor of Science in Architecture (BSArch)'),
('Bachelor of Science in Nursing (BSN)'),
('Bachelor of Science in Pharmacy (BSPharma)'),
('Bachelor of Science in Medical Technology (BSMT)'),
('Bachelor of Science in Radiologic Technology (BSRT)'),
('Bachelor of Science in Midwifery'),
('Bachelor of Science in Criminology (BS Crim)'),
('Bachelor of Science in Hospitality Management (BSHM)'),
('Bachelor of Science in Tourism Management (BSTM)'),
('Bachelor of Elementary Education (BEEd)'),
('Bachelor of Secondary Education (BSEd)'),
('Bachelor of Physical Education (BPEd)'),
('Bachelor of Science in Agriculture (BSA)'),
('Bachelor of Science in Agribusiness (BSAB)'),
('Bachelor of Science in Forestry (BSF)'),
('Bachelor of Arts in Psychology (AB Psych)'),
('Bachelor of Science in Psychology (BS Psych)'),
('Bachelor of Arts in Communication (AB Comm)'),
('Bachelor of Arts in Political Science (AB PolSci)'),
('Bachelor of Arts in English Language (AB English)'),
('Bachelor of Science in Social Work (BSSW)'),
('Bachelor of Science in Biology (BS Bio)'),
('Bachelor of Science in Mathematics (BS Math)');